'use client';

import React, { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import {
  Bell,
  FileText,
  AlertTriangle,
  DollarSign,
  CheckCheck,
  ExternalLink,
  Clock,
  User,
  MessageSquare,
  Inbox,
  CheckCircle2,
  XCircle,
  HourglassIcon,
  Plus,
  Download,
  Search as SearchIcon,
  Loader2,
} from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/store/auth-store';

/* ───────── types ───────── */
interface DeleteRequest {
  id: string;
  employeeId: string;
  requestedBy: string;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy: string | null;
  reviewedAt: string | null;
  createdAt: string;
  updatedAt: string;
  employee: {
    id: string;
    fullName: string;
    employeeId: string;
    status: string;
    position: string | null;
    nationality: string | null;
  };
  requested: { id: string; name: string; email: string };
  reviewed: { id: string; name: string; email: string } | null;
}

interface Warning {
  id: string;
  employeeId: string;
  reason: string;
  isAutoGenerated: boolean;
  absentDates: string | null;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Fine {
  id: string;
  employeeId: string;
  reason: string;
  amount: number;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'request' | 'warning' | 'fine';
  read: boolean;
  createdAt: string;
  updatedAt: string;
}

interface EmployeeOption {
  id: string;
  fullName: string;
  employeeId: string;
  phone: string | null;
  position: string | null;
  nationality: string | null;
  currentSite: string | null;
}

/* ───────── helpers ───────── */
const MONTHS = [
  { value: '01', label: 'Jan' },
  { value: '02', label: 'Feb' },
  { value: '03', label: 'Mar' },
  { value: '04', label: 'Apr' },
  { value: '05', label: 'May' },
  { value: '06', label: 'Jun' },
  { value: '07', label: 'Jul' },
  { value: '08', label: 'Aug' },
  { value: '09', label: 'Sep' },
  { value: '10', label: 'Oct' },
  { value: '11', label: 'Nov' },
  { value: '12', label: 'Dec' },
];

const currentYear = new Date().getFullYear();
const currentMonth = new Date().getMonth() + 1;
const YEARS = Array.from({ length: 5 }, (_, i) => String(currentYear - 2 + i));

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatFormalDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-SA', {
    style: 'currency',
    currency: 'SAR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(amount);
}

function generateNoticeHtml(opts: {
  type: 'warning' | 'fine';
  employeeName: string;
  employeeId: string;
  reason: string;
  date: string;
  amount?: number;
  noticeNumber?: string;
}): string {
  const isWarning = opts.type === 'warning';
  const title = isWarning ? 'NOTICE OF WARNING' : 'NOTICE OF FINE';
  const formalDate = formatFormalDate(opts.date);
  const refNumber = opts.noticeNumber || `ASM-${opts.type.toUpperCase()}-${opts.employeeId}-${new Date(opts.date).getTime().toString(36).toUpperCase()}`;

  let bodyParagraph = '';
  if (isWarning) {
    bodyParagraph = `This notice is to formally advise you that a warning has been issued against your employee record with Arabian Shield Manpower. The reason for this warning is as follows: <strong>${opts.reason}</strong>.<br/><br/>This warning has been documented in your personnel file and will be taken into consideration in any future evaluations or disciplinary proceedings. We urge you to take this matter seriously and to ensure that such behavior or incident is not repeated.<br/><br/>Please be advised that continued violations of company policies and procedures may result in further disciplinary action, up to and including termination of employment, in accordance with the labor laws of the Kingdom of Saudi Arabia.`;
  } else {
    bodyParagraph = `This notice is to formally advise you that a financial penalty has been imposed against your employee record with Arabian Shield Manpower. The reason for this fine is as follows: <strong>${opts.reason}</strong>.<br/><br/>The total amount of <strong>${formatCurrency(opts.amount || 0)} SAR</strong> is to be deducted from your upcoming salary in accordance with the company's disciplinary policy and the labor regulations of the Kingdom of Saudi Arabia. This deduction will be reflected in your next payroll cycle.<br/><br/>This fine has been documented in your personnel file and will be taken into consideration in any future evaluations or disciplinary proceedings. We urge you to take this matter seriously and to ensure full compliance with all company policies and procedures going forward.`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} - ${opts.employeeName}</title>
</head>
<body style="margin: 0; padding: 40px 20px; background-color: #f5f5f5; font-family: Georgia, 'Times New Roman', Times, serif; color: #000; -webkit-print-color-adjust: exact; print-color-adjust: exact;">
  <div style="max-width: 800px; margin: 0 auto; background: #fff; padding: 60px 60px; border: 1px solid #ccc; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">

    <!-- Company Header -->
    <div style="text-align: center; border-bottom: 3px double #1a365d; padding-bottom: 24px; margin-bottom: 32px;">
      <h1 style="margin: 0 0 4px 0; font-size: 26px; font-weight: bold; color: #1a365d; letter-spacing: 2px;">ARABIAN SHIELD MANPOWER</h1>
      <p style="margin: 0 0 4px 0; font-size: 13px; color: #4a5568;">Kingdom of Saudi Arabia</p>
      <p style="margin: 0 0 4px 0; font-size: 12px; color: #718096;">Manpower Supply &amp; Human Resources Services</p>
      <p style="margin: 0; font-size: 11px; color: #a0aec0;">Contact: info@arabianshield.com.sa | +966 XX XXX XXXX</p>
    </div>

    <!-- Notice Title -->
    <div style="text-align: center; margin-bottom: 32px;">
      <h2 style="margin: 0; font-size: 20px; font-weight: bold; color: ${isWarning ? '#b7791f' : '#c53030'}; letter-spacing: 1px; text-transform: uppercase;">${title}</h2>
      <div style="width: 80px; height: 3px; background: ${isWarning ? '#b7791f' : '#c53030'}; margin: 12px auto 0;"></div>
    </div>

    <!-- Date and Reference -->
    <div style="display: flex; justify-content: space-between; margin-bottom: 28px; font-size: 13px; color: #4a5568;">
      <div>
        <strong>Date:</strong> ${formalDate}
      </div>
      <div>
        <strong>Ref:</strong> ${refNumber}
      </div>
    </div>

    <!-- Employee Section -->
    <div style="background: #f7fafc; border: 1px solid #e2e8f0; border-radius: 4px; padding: 16px 20px; margin-bottom: 28px;">
      <p style="margin: 0 0 4px 0; font-size: 14px; color: #2d3748;"><strong>To:</strong> ${opts.employeeName}</p>
      <p style="margin: 0; font-size: 13px; color: #718096;">Employee ID: ${opts.employeeId}</p>
    </div>

    <!-- Body -->
    <div style="font-size: 14px; line-height: 1.8; color: #2d3748; margin-bottom: 32px;">
      <p style="margin: 0 0 16px 0;">Dear <strong>${opts.employeeName}</strong>,</p>
      <p style="margin: 0 0 16px 0;">${bodyParagraph}</p>
      <p style="margin: 0;">We value your contribution to our organization and expect your full cooperation in maintaining a professional and compliant work environment. Should you have any questions or wish to discuss this matter further, please contact the Human Resources Department at your earliest convenience.</p>
    </div>

    <!-- Signature -->
    <div style="margin-top: 48px; text-align: right;">
      <div style="display: inline-block; text-align: center;">
        <p style="margin: 0 0 8px 0; font-size: 14px; color: #2d3748;"><strong>Authorized by:</strong></p>
        <div style="width: 200px; border-bottom: 2px solid #2d3748; margin-bottom: 8px;"></div>
        <p style="margin: 0 0 2px 0; font-size: 14px; font-weight: bold; color: #1a365d;">ASM Management</p>
        <p style="margin: 0; font-size: 12px; color: #718096;">Human Resources Department</p>
      </div>
    </div>

    <!-- Footer -->
    <div style="margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #a0aec0; text-align: center;">
      <p style="margin: 0 0 4px 0;">This notice was generated electronically by the Arabian Shield Manpower Management System.</p>
      <p style="margin: 0 0 4px 0;">Date of issuance: ${formalDate} | Notice Reference: ${refNumber}</p>
      <p style="margin: 0;">This document is confidential and intended solely for the named recipient.</p>
    </div>

  </div>
</body>
</html>`;
}

function downloadNoticeHtml(opts: {
  type: 'warning' | 'fine';
  employeeName: string;
  employeeId: string;
  reason: string;
  date: string;
  amount?: number;
  noticeNumber?: string;
}) {
  const html = generateNoticeHtml(opts);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const datePart = new Date(opts.date).toISOString().split('T')[0];
  const filename = `${opts.type === 'warning' ? 'Warning' : 'Fine'}_${opts.employeeId}_${datePart}.html`;
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function formatWhatsAppPhone(phone: string | null): string {
  if (!phone) return '';
  let cleaned = phone.replace(/[^0-9]/g, '');
  if (cleaned.startsWith('0')) cleaned = cleaned.substring(1);
  if (cleaned.startsWith('966')) return cleaned;
  if (cleaned.length === 9) return '966' + cleaned;
  return '966' + cleaned;
}

/* ───────── Skeleton Cards ───────── */
function SkeletonCards({ count = 3 }: { count?: number }) {
  return (
    <div className="flex flex-col gap-3">
      {Array.from({ length: count }).map((_, i) => (
        <Skeleton key={i} className="h-28 w-full rounded-xl bg-slate-700/50" />
      ))}
    </div>
  );
}

/* ───────── Empty State ───────── */
function EmptyState({ icon: Icon, message }: { icon: React.ElementType; message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-700/50 mb-4">
        <Icon className="h-7 w-7 text-slate-500" />
      </div>
      <p className="text-sm text-slate-400">{message}</p>
    </div>
  );
}

/* ───────── Request Card ───────── */
function RequestCard({
  request,
  onApprove,
  onReject,
}: {
  request: DeleteRequest;
  onApprove: (id: string) => void;
  onReject: (id: string) => void;
}) {
  const statusConfig = {
    pending: { color: 'bg-amber-500/20 text-amber-400 border-amber-500/30', icon: HourglassIcon, label: 'Pending' },
    approved: { color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: CheckCircle2, label: 'Approved' },
    rejected: { color: 'bg-red-500/20 text-red-400 border-red-500/30', icon: XCircle, label: 'Rejected' },
  };
  const cfg = statusConfig[request.status];
  const StatusIcon = cfg.icon;

  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-sm font-semibold text-white truncate">
              {request.employee.fullName}
            </span>
            <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">
              {request.employee.employeeId}
            </Badge>
          </div>
          <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400">
            <span className="flex items-center gap-1">
              <User className="h-3 w-3" />
              Requested by: {request.requested.name}
            </span>
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatDate(request.createdAt)}
            </span>
            {request.employee.position && (
              <span>Position: {request.employee.position}</span>
            )}
          </div>
          {request.reviewed && request.reviewedAt && (
            <div className="mt-2 text-xs text-slate-500">
              Reviewed by {request.reviewed.name} on {formatDate(request.reviewedAt)}
            </div>
          )}
        </div>
        <div className="flex flex-col items-end gap-2 shrink-0">
          <Badge className={cn('text-xs px-2 py-0.5 border', cfg.color)}>
            <StatusIcon className="h-3 w-3 mr-1" />
            {cfg.label}
          </Badge>
          {request.status === 'pending' && (
            <div className="flex gap-1.5">
              <Button
                size="sm"
                onClick={() => onApprove(request.id)}
                className="h-7 px-2.5 bg-green-600 hover:bg-green-700 text-white text-xs"
              >
                <CheckCircle2 className="h-3.5 w-3.5 mr-1" />
                Approve
              </Button>
              <Button
                size="sm"
                onClick={() => onReject(request.id)}
                className="h-7 px-2.5 bg-red-600 hover:bg-red-700 text-white text-xs"
              >
                <XCircle className="h-3.5 w-3.5 mr-1" />
                Reject
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ───────── Warning / Fine Notification Card ───────── */
function NotificationCard({
  employeeName,
  employeeCode,
  reason,
  date,
  isUnread,
  extraInfo,
  amount,
  onMarkRead,
  onWhatsApp,
  onDownload,
  badge,
  type,
}: {
  employeeName: string;
  employeeCode: string;
  reason: string;
  date: string;
  isUnread: boolean;
  extraInfo?: React.ReactNode;
  amount?: number;
  onMarkRead?: () => void;
  onWhatsApp?: () => void;
  onDownload?: () => void;
  badge?: React.ReactNode;
  type?: 'warning' | 'fine';
}) {
  return (
    <div
      className={cn(
        'rounded-xl border p-4 transition-colors hover:bg-slate-700/40',
        isUnread
          ? 'bg-slate-800 border-l-4 border-l-blue-500 border-slate-700'
          : 'bg-slate-800/60 border-slate-700/70'
      )}
    >
      <div className="flex flex-col gap-2">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1 flex-wrap">
              {isUnread && (
                <span className="h-2 w-2 rounded-full bg-blue-500 shrink-0" />
              )}
              <span className="text-sm font-semibold text-white truncate">
                {employeeName}
              </span>
              <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400 shrink-0">
                {employeeCode}
              </Badge>
              {badge}
            </div>
            <p className="text-xs text-slate-300 line-clamp-2">{reason}</p>
            {extraInfo}
            {amount !== undefined && amount !== null && (
              <div className="mt-1">
                <span className="text-sm font-bold text-amber-400">
                  {formatCurrency(amount)}
                </span>
              </div>
            )}
          </div>
        </div>
        <div className="flex items-center justify-between mt-1">
          <span className="text-[11px] text-slate-500 flex items-center gap-1">
            <Clock className="h-3 w-3" />
            {formatDate(date)}
          </span>
          <div className="flex items-center gap-1.5">
            {isUnread && onMarkRead && (
              <Button
                variant="ghost"
                size="sm"
                onClick={onMarkRead}
                className="h-7 px-2 text-xs text-slate-400 hover:text-white hover:bg-slate-700"
              >
                <CheckCheck className="h-3 w-3 mr-1" />
                Mark Read
              </Button>
            )}
            {onWhatsApp && (
              <Button
                variant="ghost"
                size="sm"
                onClick={onWhatsApp}
                className="h-7 px-2 text-xs text-green-400 hover:text-green-300 hover:bg-green-500/10"
              >
                <MessageSquare className="h-3 w-3 mr-1" />
                WhatsApp
              </Button>
            )}
            {onDownload && (
              <Button
                variant="ghost"
                size="sm"
                onClick={onDownload}
                className="h-7 px-2 text-xs text-slate-400 hover:text-white hover:bg-slate-700"
              >
                <Download className="h-3 w-3 mr-1" />
                Download
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ───────── Employee Search Combobox ───────── */
function EmployeeSearchCombobox({
  employees,
  onSelect,
  selectedId,
}: {
  employees: EmployeeOption[];
  onSelect: (emp: EmployeeOption) => void;
  selectedId: string | null;
}) {
  const [open, setOpen] = useState(false);
  const selectedEmployee = useMemo(
    () => employees.find((e) => e.id === selectedId),
    [employees, selectedId]
  );

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between bg-slate-800 border-slate-700 text-white hover:bg-slate-700 hover:text-white text-sm"
        >
          {selectedEmployee
            ? `${selectedEmployee.fullName} (${selectedEmployee.employeeId})`
            : 'Search employees...'}
          <SearchIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0 bg-slate-800 border-slate-600" align="start">
        <Command className="bg-slate-800">
          <CommandInput placeholder="Type to search..." className="text-white" />
          <CommandList>
            <CommandEmpty className="text-slate-400">No employees found.</CommandEmpty>
            <CommandGroup>
              {employees.map((emp) => (
                <CommandItem
                  key={emp.id}
                  value={`${emp.fullName} ${emp.employeeId} ${emp.position || ''}`}
                  onSelect={() => {
                    onSelect(emp);
                    setOpen(false);
                  }}
                  className="text-slate-200 data-[selected=true]:bg-slate-700 data-[selected=true]:text-white"
                >
                  <div className="flex flex-col">
                    <span className="text-sm">{emp.fullName}</span>
                    <span className="text-[11px] text-slate-500">
                      {emp.employeeId}
                      {emp.position ? ` · ${emp.position}` : ''}
                    </span>
                  </div>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

/* ───────── Success Actions Dialog ───────── */
function SuccessActionsDialog({
  open,
  onOpenChange,
  type,
  employeeName,
  employeeId,
  reason,
  date,
  amount,
  phone,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  type: 'warning' | 'fine';
  employeeName: string;
  employeeId: string;
  reason: string;
  date: string;
  amount?: number;
  phone?: string | null;
}) {
  const whatsappPhone = phone ? formatWhatsAppPhone(phone) : '';

  const whatsappMessage = type === 'warning'
    ? `⚠️ *NOTICE OF WARNING*\n\n` +
      `*ARABIAN SHIELD MANPOWER*\n\n` +
      `Dear ${employeeName} (${employeeId}),\n\n` +
      `This is to formally notify you that a warning has been issued against your employee record.\n\n` +
      `*Reason:* ${reason}\n` +
      `*Date:* ${formatDate(date)}\n\n` +
      `This warning has been documented in your personnel file. Please ensure compliance with all company policies.\n\n` +
      `_ASM Management_`
    : `💰 *NOTICE OF FINE*\n\n` +
      `*ARABIAN SHIELD MANPOWER*\n\n` +
      `Dear ${employeeName} (${employeeId}),\n\n` +
      `This is to formally notify you that a financial penalty has been imposed against your employee record.\n\n` +
      `*Reason:* ${reason}\n` +
      `*Amount:* ${formatCurrency(amount || 0)}\n` +
      `*Date:* ${formatDate(date)}\n\n` +
      `The total amount will be deducted from your upcoming salary. Please ensure compliance with all company policies.\n\n` +
      `_ASM Management_`;

  const handleWhatsApp = () => {
    const url = whatsappPhone
      ? `https://wa.me/${whatsappPhone}?text=${encodeURIComponent(whatsappMessage)}`
      : `https://wa.me/?text=${encodeURIComponent(whatsappMessage)}`;
    window.open(url, '_blank');
  };

  const handleDownload = () => {
    downloadNoticeHtml({
      type,
      employeeName,
      employeeId,
      reason,
      date,
      amount,
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="text-green-400 flex items-center gap-2">
            <CheckCircle2 className="h-5 w-5" />
            {type === 'warning' ? 'Warning Issued Successfully' : 'Fine Issued Successfully'}
          </DialogTitle>
          <DialogDescription className="text-slate-400">
            The {type} for {employeeName} has been recorded. You can send it via WhatsApp or download the formal notice.
          </DialogDescription>
        </DialogHeader>
        <div className="flex flex-col gap-3 py-2">
          <Button
            onClick={handleWhatsApp}
            className="w-full bg-green-600 hover:bg-green-700 text-white gap-2"
          >
            <MessageSquare className="h-4 w-4" />
            Send via WhatsApp
          </Button>
          <Button
            variant="outline"
            onClick={handleDownload}
            className="w-full border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700 gap-2"
          >
            <Download className="h-4 w-4" />
            Download Notice
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

/* ───────── Requests Tab ───────── */
function RequestsTab({ userId }: { userId: string }) {
  const [requests, setRequests] = useState<DeleteRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');

  const fetchRequests = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter !== 'all') params.set('status', statusFilter);
      const res = await fetch(`/api/delete-requests?${params.toString()}`);
      const data = await res.json();
      if (data.success) {
        let filtered = data.data.deleteRequests || [];
        // Client-side year/month filter
        if (yearFilter && yearFilter !== 'all') {
          filtered = filtered.filter((r: DeleteRequest) =>
            r.createdAt.startsWith(yearFilter)
          );
        }
        if (monthFilter && monthFilter !== 'all') {
          filtered = filtered.filter((r: DeleteRequest) =>
            r.createdAt.substring(5, 7) === monthFilter
          );
        }
        setRequests(filtered);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch delete requests', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [statusFilter, yearFilter, monthFilter]);

  useEffect(() => { fetchRequests(); }, [fetchRequests]);

  const handleReview = async (id: string, status: 'approved' | 'rejected') => {
    try {
      const res = await fetch(`/api/delete-requests/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status, reviewedBy: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({
          title: status === 'approved' ? 'Approved' : 'Rejected',
          description: `Delete request has been ${status}`,
        });
        fetchRequests();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to update', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to update request', variant: 'destructive' });
    }
  };

  const pendingCount = requests.filter((r) => r.status === 'pending').length;

  return (
    <div className="flex flex-col gap-4">
      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2">
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-32 bg-slate-800 border-slate-700 text-sm text-white">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
            <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All</SelectItem>
            <SelectItem value="pending" className="text-slate-200 focus:bg-slate-700 focus:text-white">Pending</SelectItem>
            <SelectItem value="approved" className="text-slate-200 focus:bg-slate-700 focus:text-white">Approved</SelectItem>
            <SelectItem value="rejected" className="text-slate-200 focus:bg-slate-700 focus:text-white">Rejected</SelectItem>
          </SelectContent>
        </Select>
        <Select value={yearFilter} onValueChange={setYearFilter}>
          <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
            <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Years</SelectItem>
            {YEARS.map((y) => (
              <SelectItem key={y} value={y} className="text-slate-200 focus:bg-slate-700 focus:text-white">{y}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={monthFilter} onValueChange={setMonthFilter}>
          <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="dropdown-upward bg-slate-800 border-slate-600 max-h-64">
            <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Months</SelectItem>
            {MONTHS.map((m) => (
              <SelectItem key={m.value} value={m.value} className="text-slate-200 focus:bg-slate-700 focus:text-white">{m.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        {pendingCount > 0 && (
          <Badge className="bg-amber-500/20 text-amber-400 border border-amber-500/30 text-xs px-2 py-0.5">
            {pendingCount} pending
          </Badge>
        )}
      </div>

      {/* List */}
      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? (
          <SkeletonCards count={3} />
        ) : requests.length === 0 ? (
          <EmptyState icon={FileText} message="No delete requests found" />
        ) : (
          requests.map((req) => (
            <RequestCard
              key={req.id}
              request={req}
              onApprove={(id) => handleReview(id, 'approved')}
              onReject={(id) => handleReview(id, 'rejected')}
            />
          ))
        )}
      </div>
    </div>
  );
}

/* ───────── Warnings Tab ───────── */
function WarningsTab({ userId }: { userId: string }) {
  const [warnings, setWarnings] = useState<Warning[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');

  // Create warning dialog state
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [warningReason, setWarningReason] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  // Success actions dialog state
  const [successDialogOpen, setSuccessDialogOpen] = useState(false);
  const [lastCreated, setLastCreated] = useState<{
    employeeName: string;
    employeeId: string;
    reason: string;
    date: string;
    phone: string | null;
  } | null>(null);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(
          data.data.employees.map((e: { id: string; fullName: string; employeeId: string; phone: string | null; position: string | null; nationality: string | null; currentSite: string | null }) => ({
            id: e.id,
            fullName: e.fullName,
            employeeId: e.employeeId,
            phone: e.phone,
            position: e.position,
            nationality: e.nationality,
            currentSite: e.currentSite,
          }))
        );
      }
    } catch {
      // silently fail
    } finally {
      setEmployeesLoading(false);
    }
  }, []);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setWarningReason('');
    if (employees.length === 0) {
      fetchEmployees();
    }
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [warningsRes, notifsRes] = await Promise.all([
        fetch('/api/warnings'),
        fetch('/api/notifications?type=warning'),
      ]);
      const [warningsData, notifsData] = await Promise.all([warningsRes.json(), notifsRes.json()]);

      if (warningsData.success) {
        let filtered = warningsData.data.warnings || [];
        if (yearFilter && yearFilter !== 'all') {
          filtered = filtered.filter((w: Warning) => w.createdAt.startsWith(yearFilter));
        }
        if (monthFilter && monthFilter !== 'all') {
          filtered = filtered.filter((w: Warning) => w.createdAt.substring(5, 7) === monthFilter);
        }
        setWarnings(filtered);
      }
      if (notifsData.success) {
        setNotifications(notifsData.data.notifications || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch warnings', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [yearFilter, monthFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const isUnread = (warningId: string) => {
    return notifications.some((n) => !n.read && n.type === 'warning' && n.message.includes(warningId.slice(-6)));
  };

  const handleMarkRead = async (warningId: string) => {
    try {
      const relatedNotifs = notifications.filter(
        (n) => !n.read && n.type === 'warning' && n.message.includes(warningId.slice(-6))
      );
      for (const n of relatedNotifs) {
        await fetch(`/api/notifications/${n.id}`, { method: 'PUT' });
      }
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'Marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark as read', variant: 'destructive' });
    }
  };

  const handleWhatsApp = (warning: Warning) => {
    const message = `⚠️ *Warning Notification*\n\n` +
      `👤 Employee: ${warning.employee.fullName}\n` +
      `🆔 ID: ${warning.employee.employeeId}\n` +
      `📋 Reason: ${warning.reason}\n` +
      `📅 Date: ${formatDate(warning.createdAt)}\n` +
      (warning.isAutoGenerated ? '🤖 Auto-generated warning\n' : '') +
      `\n_ASM Management System_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  const handleDownload = (warning: Warning) => {
    downloadNoticeHtml({
      type: 'warning',
      employeeName: warning.employee.fullName,
      employeeId: warning.employee.employeeId,
      reason: warning.reason,
      date: warning.createdAt,
    });
  };

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ markAll: true, type: 'warning' }),
      });
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'All warnings marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' });
    }
  };

  const handleCreateWarning = async () => {
    if (!selectedEmployee || !warningReason.trim()) {
      toast({ title: 'Validation Error', description: 'Please select an employee and provide a reason.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/warnings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          employeeId: selectedEmployee.id,
          reason: warningReason.trim(),
          createdById: userId,
        }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Warning Issued', description: `Warning issued to ${selectedEmployee.fullName}` });
        setCreateDialogOpen(false);
        setLastCreated({
          employeeName: selectedEmployee.fullName,
          employeeId: selectedEmployee.employeeId,
          reason: warningReason.trim(),
          date: new Date().toISOString(),
          phone: selectedEmployee.phone,
        });
        setSuccessDialogOpen(true);
        fetchData();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to create warning', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to create warning', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  const unreadCount = notifications.filter((n) => !n.read && n.type === 'warning').length;

  return (
    <div className="flex flex-col gap-4">
      {/* Filters */}
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <Select value={yearFilter} onValueChange={setYearFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Years</SelectItem>
              {YEARS.map((y) => (
                <SelectItem key={y} value={y} className="text-slate-200 focus:bg-slate-700 focus:text-white">{y}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={monthFilter} onValueChange={setMonthFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600 max-h-64">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Months</SelectItem>
              {MONTHS.map((m) => (
                <SelectItem key={m.value} value={m.value} className="text-slate-200 focus:bg-slate-700 focus:text-white">{m.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="flex items-center gap-2">
          <Button
            size="sm"
            onClick={openCreateDialog}
            className="h-8 bg-amber-600 hover:bg-amber-700 text-white text-xs gap-1.5"
          >
            <Plus className="h-3.5 w-3.5" />
            Issue Warning
          </Button>
          {unreadCount > 0 && (
            <Button
              variant="ghost"
              size="sm"
              onClick={handleMarkAllRead}
              className="h-8 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-500/10"
            >
              <CheckCheck className="h-3.5 w-3.5 mr-1" />
              Mark All Read ({unreadCount})
            </Button>
          )}
        </div>
      </div>

      {/* List */}
      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? (
          <SkeletonCards count={3} />
        ) : warnings.length === 0 ? (
          <EmptyState icon={AlertTriangle} message="No warnings found" />
        ) : (
          warnings.map((w) => {
            const unread = isUnread(w.id);
            let absentDatesList: string[] = [];
            if (w.absentDates) {
              try { absentDatesList = JSON.parse(w.absentDates); } catch { /* ignore */ }
            }
            return (
              <NotificationCard
                key={w.id}
                type="warning"
                employeeName={w.employee.fullName}
                employeeCode={w.employee.employeeId}
                reason={w.reason}
                date={w.createdAt}
                isUnread={unread}
                onMarkRead={() => handleMarkRead(w.id)}
                onWhatsApp={() => handleWhatsApp(w)}
                onDownload={() => handleDownload(w)}
                badge={
                  w.isAutoGenerated ? (
                    <Badge className="bg-purple-500/20 text-purple-400 border border-purple-500/30 text-[10px] px-1.5 py-0">
                      Auto
                    </Badge>
                  ) : undefined
                }
                extraInfo={
                  absentDatesList.length > 0 ? (
                    <div className="mt-1 flex flex-wrap gap-1">
                      <span className="text-[11px] text-slate-500">Absent dates:</span>
                      {absentDatesList.slice(0, 5).map((d) => (
                        <Badge key={d} variant="outline" className="text-[10px] px-1 py-0 border-slate-600 text-slate-400">
                          {formatDate(d)}
                        </Badge>
                      ))}
                      {absentDatesList.length > 5 && (
                        <span className="text-[10px] text-slate-500">+{absentDatesList.length - 5} more</span>
                      )}
                    </div>
                  ) : undefined
                }
              />
            );
          })
        )}
      </div>

      {/* Create Warning Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-amber-400" />
              Issue Warning
            </DialogTitle>
            <DialogDescription className="text-slate-400">
              Select an employee and provide the reason for the warning.
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div className="flex flex-col gap-2">
              <Label className="text-sm text-slate-300">Employee</Label>
              {employeesLoading ? (
                <div className="flex items-center gap-2 text-sm text-slate-400 py-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Loading employees...
                </div>
              ) : (
                <EmployeeSearchCombobox
                  employees={employees}
                  onSelect={setSelectedEmployee}
                  selectedId={selectedEmployee?.id || null}
                />
              )}
            </div>
            <div className="flex flex-col gap-2">
              <Label className="text-sm text-slate-300">Reason <span className="text-red-400">*</span></Label>
              <Textarea
                value={warningReason}
                onChange={(e) => setWarningReason(e.target.value)}
                placeholder="Enter the reason for the warning..."
                className="min-h-[100px] bg-slate-900 border-slate-700 text-white placeholder:text-slate-500 resize-none"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setCreateDialogOpen(false)}
              className="border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700"
              disabled={submitting}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateWarning}
              disabled={submitting || !selectedEmployee || !warningReason.trim()}
              className="bg-amber-600 hover:bg-amber-700 text-white gap-2"
            >
              {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
              {submitting ? 'Issuing...' : 'Issue Warning'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Success Actions Dialog */}
      {lastCreated && (
        <SuccessActionsDialog
          open={successDialogOpen}
          onOpenChange={setSuccessDialogOpen}
          type="warning"
          employeeName={lastCreated.employeeName}
          employeeId={lastCreated.employeeId}
          reason={lastCreated.reason}
          date={lastCreated.date}
          phone={lastCreated.phone}
        />
      )}
    </div>
  );
}

/* ───────── Fines Tab ───────── */
function FinesTab({ userId }: { userId: string }) {
  const [fines, setFines] = useState<Fine[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');

  // Create fine dialog state
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [fineReason, setFineReason] = useState('');
  const [fineAmount, setFineAmount] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  // Success actions dialog state
  const [successDialogOpen, setSuccessDialogOpen] = useState(false);
  const [lastCreated, setLastCreated] = useState<{
    employeeName: string;
    employeeId: string;
    reason: string;
    date: string;
    amount: number;
    phone: string | null;
  } | null>(null);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(
          data.data.employees.map((e: { id: string; fullName: string; employeeId: string; phone: string | null; position: string | null; nationality: string | null; currentSite: string | null }) => ({
            id: e.id,
            fullName: e.fullName,
            employeeId: e.employeeId,
            phone: e.phone,
            position: e.position,
            nationality: e.nationality,
            currentSite: e.currentSite,
          }))
        );
      }
    } catch {
      // silently fail
    } finally {
      setEmployeesLoading(false);
    }
  }, []);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setFineReason('');
    setFineAmount('');
    if (employees.length === 0) {
      fetchEmployees();
    }
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [finesRes, notifsRes] = await Promise.all([
        fetch('/api/fines'),
        fetch('/api/notifications?type=fine'),
      ]);
      const [finesData, notifsData] = await Promise.all([finesRes.json(), notifsRes.json()]);

      if (finesData.success) {
        let filtered = finesData.data.fines || [];
        if (yearFilter && yearFilter !== 'all') {
          filtered = filtered.filter((f: Fine) => f.createdAt.startsWith(yearFilter));
        }
        if (monthFilter && monthFilter !== 'all') {
          filtered = filtered.filter((f: Fine) => f.createdAt.substring(5, 7) === monthFilter);
        }
        setFines(filtered);
      }
      if (notifsData.success) {
        setNotifications(notifsData.data.notifications || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch fines', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [yearFilter, monthFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const isUnread = (fineId: string) => {
    return notifications.some((n) => !n.read && n.type === 'fine' && n.message.includes(fineId.slice(-6)));
  };

  const handleMarkRead = async (fineId: string) => {
    try {
      const relatedNotifs = notifications.filter(
        (n) => !n.read && n.type === 'fine' && n.message.includes(fineId.slice(-6))
      );
      for (const n of relatedNotifs) {
        await fetch(`/api/notifications/${n.id}`, { method: 'PUT' });
      }
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'Marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark as read', variant: 'destructive' });
    }
  };

  const handleWhatsApp = (fine: Fine) => {
    const message = `💰 *Fine Notification*\n\n` +
      `👤 Employee: ${fine.employee.fullName}\n` +
      `🆔 ID: ${fine.employee.employeeId}\n` +
      `📋 Reason: ${fine.reason}\n` +
      `💵 Amount: ${formatCurrency(fine.amount)}\n` +
      `📅 Date: ${formatDate(fine.createdAt)}\n` +
      `\n_ASM Management System_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  const handleDownload = (fine: Fine) => {
    downloadNoticeHtml({
      type: 'fine',
      employeeName: fine.employee.fullName,
      employeeId: fine.employee.employeeId,
      reason: fine.reason,
      date: fine.createdAt,
      amount: fine.amount,
    });
  };

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ markAll: true, type: 'fine' }),
      });
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'All fines marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' });
    }
  };

  const handleCreateFine = async () => {
    if (!selectedEmployee || !fineReason.trim() || !fineAmount || isNaN(Number(fineAmount)) || Number(fineAmount) <= 0) {
      toast({ title: 'Validation Error', description: 'Please select an employee, provide a reason, and enter a valid amount.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/fines', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          employeeId: selectedEmployee.id,
          reason: fineReason.trim(),
          amount: Number(fineAmount),
          createdById: userId,
        }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Fine Issued', description: `Fine of ${formatCurrency(Number(fineAmount))} issued to ${selectedEmployee.fullName}` });
        setCreateDialogOpen(false);
        setLastCreated({
          employeeName: selectedEmployee.fullName,
          employeeId: selectedEmployee.employeeId,
          reason: fineReason.trim(),
          date: new Date().toISOString(),
          amount: Number(fineAmount),
          phone: selectedEmployee.phone,
        });
        setSuccessDialogOpen(true);
        fetchData();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to create fine', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to create fine', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  const unreadCount = notifications.filter((n) => !n.read && n.type === 'fine').length;
  const totalFines = fines.reduce((sum, f) => sum + f.amount, 0);

  return (
    <div className="flex flex-col gap-4">
      {/* Summary + Filters */}
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <Select value={yearFilter} onValueChange={setYearFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Years</SelectItem>
              {YEARS.map((y) => (
                <SelectItem key={y} value={y} className="text-slate-200 focus:bg-slate-700 focus:text-white">{y}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={monthFilter} onValueChange={setMonthFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600 max-h-64">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Months</SelectItem>
              {MONTHS.map((m) => (
                <SelectItem key={m.value} value={m.value} className="text-slate-200 focus:bg-slate-700 focus:text-white">{m.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          {fines.length > 0 && (
            <Badge className="bg-amber-500/20 text-amber-400 border border-amber-500/30 text-xs px-2 py-0.5">
              Total: {formatCurrency(totalFines)}
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-2">
          <Button
            size="sm"
            onClick={openCreateDialog}
            className="h-8 bg-red-600 hover:bg-red-700 text-white text-xs gap-1.5"
          >
            <Plus className="h-3.5 w-3.5" />
            Issue Fine
          </Button>
          {unreadCount > 0 && (
            <Button
              variant="ghost"
              size="sm"
              onClick={handleMarkAllRead}
              className="h-8 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-500/10"
            >
              <CheckCheck className="h-3.5 w-3.5 mr-1" />
              Mark All Read ({unreadCount})
            </Button>
          )}
        </div>
      </div>

      {/* List */}
      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? (
          <SkeletonCards count={3} />
        ) : fines.length === 0 ? (
          <EmptyState icon={DollarSign} message="No fines found" />
        ) : (
          fines.map((f) => (
            <NotificationCard
              key={f.id}
              type="fine"
              employeeName={f.employee.fullName}
              employeeCode={f.employee.employeeId}
              reason={f.reason}
              date={f.createdAt}
              isUnread={isUnread(f.id)}
              amount={f.amount}
              onMarkRead={() => handleMarkRead(f.id)}
              onWhatsApp={() => handleWhatsApp(f)}
              onDownload={() => handleDownload(f)}
            />
          ))
        )}
      </div>

      {/* Create Fine Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-red-400" />
              Issue Fine
            </DialogTitle>
            <DialogDescription className="text-slate-400">
              Select an employee, provide the reason and amount for the fine.
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div className="flex flex-col gap-2">
              <Label className="text-sm text-slate-300">Employee</Label>
              {employeesLoading ? (
                <div className="flex items-center gap-2 text-sm text-slate-400 py-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Loading employees...
                </div>
              ) : (
                <EmployeeSearchCombobox
                  employees={employees}
                  onSelect={setSelectedEmployee}
                  selectedId={selectedEmployee?.id || null}
                />
              )}
            </div>
            <div className="flex flex-col gap-2">
              <Label className="text-sm text-slate-300">Reason <span className="text-red-400">*</span></Label>
              <Textarea
                value={fineReason}
                onChange={(e) => setFineReason(e.target.value)}
                placeholder="Enter the reason for the fine..."
                className="min-h-[100px] bg-slate-900 border-slate-700 text-white placeholder:text-slate-500 resize-none"
              />
            </div>
            <div className="flex flex-col gap-2">
              <Label className="text-sm text-slate-300">Amount (SAR) <span className="text-red-400">*</span></Label>
              <Input
                type="number"
                min="1"
                step="0.01"
                value={fineAmount}
                onChange={(e) => setFineAmount(e.target.value)}
                placeholder="Enter amount in SAR"
                className="bg-slate-900 border-slate-700 text-white placeholder:text-slate-500"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setCreateDialogOpen(false)}
              className="border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700"
              disabled={submitting}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateFine}
              disabled={submitting || !selectedEmployee || !fineReason.trim() || !fineAmount || isNaN(Number(fineAmount)) || Number(fineAmount) <= 0}
              className="bg-red-600 hover:bg-red-700 text-white gap-2"
            >
              {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
              {submitting ? 'Issuing...' : 'Issue Fine'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Success Actions Dialog */}
      {lastCreated && (
        <SuccessActionsDialog
          open={successDialogOpen}
          onOpenChange={setSuccessDialogOpen}
          type="fine"
          employeeName={lastCreated.employeeName}
          employeeId={lastCreated.employeeId}
          reason={lastCreated.reason}
          date={lastCreated.date}
          amount={lastCreated.amount}
          phone={lastCreated.phone}
        />
      )}
    </div>
  );
}

/* ───────── Main Page ───────── */
export function NotificationPage() {
  const { user } = useAuthStore();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(true);

  const fetchNotifications = useCallback(async () => {
    try {
      const res = await fetch('/api/notifications?limit=100');
      const data = await res.json();
      if (data.success) {
        const notifs: Notification[] = data.data.notifications || [];
        setNotifications(notifs);
        setUnreadCount(notifs.filter((n) => !n.read).length);
      }
    } catch {
      // Silently fail for the count
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchNotifications(); }, [fetchNotifications]);

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ markAll: true }),
      });
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      setUnreadCount(0);
      toast({ title: 'All notifications marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' });
    }
  };

  const userId = user?.id || '';

  return (
    <div className="flex flex-col gap-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10">
            <Bell className="h-5 w-5 text-blue-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white flex items-center gap-2">
              Notifications
              {!loading && unreadCount > 0 && (
                <Badge className="bg-blue-500 text-white text-xs px-2 py-0.5">
                  {unreadCount}
                </Badge>
              )}
            </h2>
            <p className="text-slate-400 mt-0.5 text-sm">
              Stay updated with requests, warnings, and fines
            </p>
          </div>
        </div>
        {unreadCount > 0 && (
          <Button
            variant="outline"
            size="sm"
            onClick={handleMarkAllRead}
            className="h-8 border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700 text-xs"
          >
            <CheckCheck className="h-3.5 w-3.5 mr-1.5" />
            Mark All Read
          </Button>
        )}
      </div>

      {/* Tabs */}
      <Tabs defaultValue="requests" className="w-full">
        <TabsList className="bg-slate-800 border border-slate-700/50">
          <TabsTrigger
            value="requests"
            className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"
          >
            <FileText className="h-4 w-4" />
            Requests
          </TabsTrigger>
          <TabsTrigger
            value="warnings"
            className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"
          >
            <AlertTriangle className="h-4 w-4" />
            Warnings
          </TabsTrigger>
          <TabsTrigger
            value="fines"
            className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"
          >
            <DollarSign className="h-4 w-4" />
            Fines
          </TabsTrigger>
        </TabsList>

        <TabsContent value="requests" className="mt-4">
          <RequestsTab userId={userId} />
        </TabsContent>

        <TabsContent value="warnings" className="mt-4">
          <WarningsTab userId={userId} />
        </TabsContent>

        <TabsContent value="fines" className="mt-4">
          <FinesTab userId={userId} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
