'use client';

import React, { useState, useEffect, useCallback } from 'react';
import {
  Bell,
  FileText,
  AlertTriangle,
  DollarSign,
  CheckCheck,
  ExternalLink,
  Clock,
  User,
  MessageSquare,
  Inbox,
  CheckCircle2,
  XCircle,
  HourglassIcon,
} from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/store/auth-store';

/* ───────── types ───────── */
interface DeleteRequest {
  id: string;
  employeeId: string;
  requestedBy: string;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy: string | null;
  reviewedAt: string | null;
  createdAt: string;
  updatedAt: string;
  employee: {
    id: string;
    fullName: string;
    employeeId: string;
    status: string;
    position: string | null;
    nationality: string | null;
  };
  requested: { id: string; name: string; email: string };
  reviewed: { id: string; name: string; email: string } | null;
}

interface Warning {
  id: string;
  employeeId: string;
  reason: string;
  isAutoGenerated: boolean;
  absentDates: string | null;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Fine {
  id: string;
  employeeId: string;
  reason: string;
  amount: number;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'request' | 'warning' | 'fine';
  read: boolean;
  createdAt: string;
  updatedAt: string;
}

/* ───────── helpers ───────── */
const MONTHS = [
  { value: '01', label: 'Jan' },
  { value: '02', label: 'Feb' },
  { value: '03', label: 'Mar' },
  { value: '04', label: 'Apr' },
  { value: '05', label: 'May' },
  { value: '06', label: 'Jun' },
  { value: '07', label: 'Jul' },
  { value: '08', label: 'Aug' },
  { value: '09', label: 'Sep' },
  { value: '10', label: 'Oct' },
  { value: '11', label: 'Nov' },
  { value: '12', label: 'Dec' },
];

const currentYear = new Date().getFullYear();
const currentMonth = new Date().getMonth() + 1;
const YEARS = Array.from({ length: 5 }, (_, i) => String(currentYear - 2 + i));

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-SA', {
    style: 'currency',
    currency: 'SAR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(amount);
}

/* ───────── Skeleton Cards ───────── */
function SkeletonCards({ count = 3 }: { count?: number }) {
  return (
    <div className="flex flex-col gap-3">
      {Array.from({ length: count }).map((_, i) => (
        <Skeleton key={i} className="h-28 w-full rounded-xl bg-slate-700/50" />
      ))}
    </div>
  );
}

/* ───────── Empty State ───────── */
function EmptyState({ icon: Icon, message }: { icon: React.ElementType; message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-700/50 mb-4">
        <Icon className="h-7 w-7 text-slate-500" />
      </div>
      <p className="text-sm text-slate-400">{message}</p>
    </div>
  );
}

/* ───────── Request Card ───────── */
function RequestCard({
  request,
  onApprove,
  onReject,
}: {
  request: DeleteRequest;
  onApprove: (id: string) => void;
  onReject: (id: string) => void;
}) {
  const statusConfig = {
    pending: { color: 'bg-amber-500/20 text-amber-400 border-amber-500/30', icon: HourglassIcon, label: 'Pending' },
    approved: { color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: CheckCircle2, label: 'Approved' },
    rejected: { color: 'bg-red-500/20 text-red-400 border-red-500/30', icon: XCircle, label: 'Rejected' },
  };
  const cfg = statusConfig[request.status];
  const StatusIcon = cfg.icon;

  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-sm font-semibold text-white truncate">
              {request.employee.fullName}
            </span>
            <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">
              {request.employee.employeeId}
            </Badge>
          </div>
          <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400">
            <span className="flex items-center gap-1">
              <User className="h-3 w-3" />
              Requested by: {request.requested.name}
            </span>
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatDate(request.createdAt)}
            </span>
            {request.employee.position && (
              <span>Position: {request.employee.position}</span>
            )}
          </div>
          {request.reviewed && request.reviewedAt && (
            <div className="mt-2 text-xs text-slate-500">
              Reviewed by {request.reviewed.name} on {formatDate(request.reviewedAt)}
            </div>
          )}
        </div>
        <div className="flex flex-col items-end gap-2 shrink-0">
          <Badge className={cn('text-xs px-2 py-0.5 border', cfg.color)}>
            <StatusIcon className="h-3 w-3 mr-1" />
            {cfg.label}
          </Badge>
          {request.status === 'pending' && (
            <div className="flex gap-1.5">
              <Button
                size="sm"
                onClick={() => onApprove(request.id)}
                className="h-7 px-2.5 bg-green-600 hover:bg-green-700 text-white text-xs"
              >
                <CheckCircle2 className="h-3.5 w-3.5 mr-1" />
                Approve
              </Button>
              <Button
                size="sm"
                onClick={() => onReject(request.id)}
                className="h-7 px-2.5 bg-red-600 hover:bg-red-700 text-white text-xs"
              >
                <XCircle className="h-3.5 w-3.5 mr-1" />
                Reject
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ───────── Warning / Fine Notification Card ───────── */
function NotificationCard({
  employeeName,
  employeeCode,
  reason,
  date,
  isUnread,
  extraInfo,
  amount,
  onMarkRead,
  onWhatsApp,
  badge,
}: {
  employeeName: string;
  employeeCode: string;
  reason: string;
  date: string;
  isUnread: boolean;
  extraInfo?: React.ReactNode;
  amount?: number;
  onMarkRead?: () => void;
  onWhatsApp?: () => void;
  badge?: React.ReactNode;
}) {
  return (
    <div
      className={cn(
        'rounded-xl border p-4 transition-colors hover:bg-slate-700/40',
        isUnread
          ? 'bg-slate-800 border-l-4 border-l-blue-500 border-slate-700'
          : 'bg-slate-800/60 border-slate-700/70'
      )}
    >
      <div className="flex flex-col gap-2">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1 flex-wrap">
              {isUnread && (
                <span className="h-2 w-2 rounded-full bg-blue-500 shrink-0" />
              )}
              <span className="text-sm font-semibold text-white truncate">
                {employeeName}
              </span>
              <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400 shrink-0">
                {employeeCode}
              </Badge>
              {badge}
            </div>
            <p className="text-xs text-slate-300 line-clamp-2">{reason}</p>
            {extraInfo}
            {amount !== undefined && amount !== null && (
              <div className="mt-1">
                <span className="text-sm font-bold text-amber-400">
                  {formatCurrency(amount)}
                </span>
              </div>
            )}
          </div>
        </div>
        <div className="flex items-center justify-between mt-1">
          <span className="text-[11px] text-slate-500 flex items-center gap-1">
            <Clock className="h-3 w-3" />
            {formatDate(date)}
          </span>
          <div className="flex items-center gap-1.5">
            {isUnread && onMarkRead && (
              <Button
                variant="ghost"
                size="sm"
                onClick={onMarkRead}
                className="h-7 px-2 text-xs text-slate-400 hover:text-white hover:bg-slate-700"
              >
                <CheckCheck className="h-3 w-3 mr-1" />
                Mark Read
              </Button>
            )}
            {onWhatsApp && (
              <Button
                variant="ghost"
                size="sm"
                onClick={onWhatsApp}
                className="h-7 px-2 text-xs text-green-400 hover:text-green-300 hover:bg-green-500/10"
              >
                <MessageSquare className="h-3 w-3 mr-1" />
                WhatsApp
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ───────── Requests Tab ───────── */
function RequestsTab({ userId }: { userId: string }) {
  const [requests, setRequests] = useState<DeleteRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');

  const fetchRequests = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter !== 'all') params.set('status', statusFilter);
      const res = await fetch(`/api/delete-requests?${params.toString()}`);
      const data = await res.json();
      if (data.success) {
        let filtered = data.data.deleteRequests || [];
        // Client-side year/month filter
        if (yearFilter && yearFilter !== 'all') {
          filtered = filtered.filter((r: DeleteRequest) =>
            r.createdAt.startsWith(yearFilter)
          );
        }
        if (monthFilter && monthFilter !== 'all') {
          filtered = filtered.filter((r: DeleteRequest) =>
            r.createdAt.substring(5, 7) === monthFilter
          );
        }
        setRequests(filtered);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch delete requests', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [statusFilter, yearFilter, monthFilter]);

  useEffect(() => { fetchRequests(); }, [fetchRequests]);

  const handleReview = async (id: string, status: 'approved' | 'rejected') => {
    try {
      const res = await fetch(`/api/delete-requests/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status, reviewedBy: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({
          title: status === 'approved' ? 'Approved' : 'Rejected',
          description: `Delete request has been ${status}`,
        });
        fetchRequests();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to update', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to update request', variant: 'destructive' });
    }
  };

  const pendingCount = requests.filter((r) => r.status === 'pending').length;

  return (
    <div className="flex flex-col gap-4">
      {/* Filters */}
      <div className="flex flex-wrap items-center gap-2">
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-32 bg-slate-800 border-slate-700 text-sm text-white">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
            <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All</SelectItem>
            <SelectItem value="pending" className="text-slate-200 focus:bg-slate-700 focus:text-white">Pending</SelectItem>
            <SelectItem value="approved" className="text-slate-200 focus:bg-slate-700 focus:text-white">Approved</SelectItem>
            <SelectItem value="rejected" className="text-slate-200 focus:bg-slate-700 focus:text-white">Rejected</SelectItem>
          </SelectContent>
        </Select>
        <Select value={yearFilter} onValueChange={setYearFilter}>
          <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
            <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Years</SelectItem>
            {YEARS.map((y) => (
              <SelectItem key={y} value={y} className="text-slate-200 focus:bg-slate-700 focus:text-white">{y}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={monthFilter} onValueChange={setMonthFilter}>
          <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="dropdown-upward bg-slate-800 border-slate-600 max-h-64">
            <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Months</SelectItem>
            {MONTHS.map((m) => (
              <SelectItem key={m.value} value={m.value} className="text-slate-200 focus:bg-slate-700 focus:text-white">{m.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        {pendingCount > 0 && (
          <Badge className="bg-amber-500/20 text-amber-400 border border-amber-500/30 text-xs px-2 py-0.5">
            {pendingCount} pending
          </Badge>
        )}
      </div>

      {/* List */}
      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? (
          <SkeletonCards count={3} />
        ) : requests.length === 0 ? (
          <EmptyState icon={FileText} message="No delete requests found" />
        ) : (
          requests.map((req) => (
            <RequestCard
              key={req.id}
              request={req}
              onApprove={(id) => handleReview(id, 'approved')}
              onReject={(id) => handleReview(id, 'rejected')}
            />
          ))
        )}
      </div>
    </div>
  );
}

/* ───────── Warnings Tab ───────── */
function WarningsTab({ userId }: { userId: string }) {
  const [warnings, setWarnings] = useState<Warning[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [warningsRes, notifsRes] = await Promise.all([
        fetch('/api/warnings'),
        fetch('/api/notifications?type=warning'),
      ]);
      const [warningsData, notifsData] = await Promise.all([warningsRes.json(), notifsRes.json()]);

      if (warningsData.success) {
        let filtered = warningsData.data.warnings || [];
        if (yearFilter && yearFilter !== 'all') {
          filtered = filtered.filter((w: Warning) => w.createdAt.startsWith(yearFilter));
        }
        if (monthFilter && monthFilter !== 'all') {
          filtered = filtered.filter((w: Warning) => w.createdAt.substring(5, 7) === monthFilter);
        }
        setWarnings(filtered);
      }
      if (notifsData.success) {
        setNotifications(notifsData.data.notifications || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch warnings', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [yearFilter, monthFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const isUnread = (warningId: string) => {
    return notifications.some((n) => !n.read && n.type === 'warning' && n.message.includes(warningId.slice(-6)));
  };

  const handleMarkRead = async (warningId: string) => {
    try {
      const relatedNotifs = notifications.filter(
        (n) => !n.read && n.type === 'warning' && n.message.includes(warningId.slice(-6))
      );
      for (const n of relatedNotifs) {
        await fetch(`/api/notifications/${n.id}`, { method: 'PUT' });
      }
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'Marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark as read', variant: 'destructive' });
    }
  };

  const handleWhatsApp = (warning: Warning) => {
    const message = `⚠️ *Warning Notification*\n\n` +
      `👤 Employee: ${warning.employee.fullName}\n` +
      `🆔 ID: ${warning.employee.employeeId}\n` +
      `📋 Reason: ${warning.reason}\n` +
      `📅 Date: ${formatDate(warning.createdAt)}\n` +
      (warning.isAutoGenerated ? '🤖 Auto-generated warning\n' : '') +
      `\n_ASM Management System_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ markAll: true, type: 'warning' }),
      });
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'All warnings marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' });
    }
  };

  const unreadCount = notifications.filter((n) => !n.read && n.type === 'warning').length;

  let parsedAbsentDates: string[] = [];
  try {
    parsedAbsentDates = warnings.length > 0 && warnings[0].absentDates
      ? JSON.parse(warnings[0].absentDates) : [];
  } catch {
    // ignore
  }

  return (
    <div className="flex flex-col gap-4">
      {/* Filters */}
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <Select value={yearFilter} onValueChange={setYearFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Years</SelectItem>
              {YEARS.map((y) => (
                <SelectItem key={y} value={y} className="text-slate-200 focus:bg-slate-700 focus:text-white">{y}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={monthFilter} onValueChange={setMonthFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600 max-h-64">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Months</SelectItem>
              {MONTHS.map((m) => (
                <SelectItem key={m.value} value={m.value} className="text-slate-200 focus:bg-slate-700 focus:text-white">{m.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        {unreadCount > 0 && (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleMarkAllRead}
            className="h-8 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-500/10"
          >
            <CheckCheck className="h-3.5 w-3.5 mr-1" />
            Mark All Read ({unreadCount})
          </Button>
        )}
      </div>

      {/* List */}
      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? (
          <SkeletonCards count={3} />
        ) : warnings.length === 0 ? (
          <EmptyState icon={AlertTriangle} message="No warnings found" />
        ) : (
          warnings.map((w) => {
            const unread = isUnread(w.id);
            let absentDatesList: string[] = [];
            if (w.absentDates) {
              try { absentDatesList = JSON.parse(w.absentDates); } catch { /* ignore */ }
            }
            return (
              <NotificationCard
                key={w.id}
                employeeName={w.employee.fullName}
                employeeCode={w.employee.employeeId}
                reason={w.reason}
                date={w.createdAt}
                isUnread={unread}
                onMarkRead={() => handleMarkRead(w.id)}
                onWhatsApp={() => handleWhatsApp(w)}
                badge={
                  w.isAutoGenerated ? (
                    <Badge className="bg-purple-500/20 text-purple-400 border border-purple-500/30 text-[10px] px-1.5 py-0">
                      Auto
                    </Badge>
                  ) : undefined
                }
                extraInfo={
                  absentDatesList.length > 0 ? (
                    <div className="mt-1 flex flex-wrap gap-1">
                      <span className="text-[11px] text-slate-500">Absent dates:</span>
                      {absentDatesList.slice(0, 5).map((d) => (
                        <Badge key={d} variant="outline" className="text-[10px] px-1 py-0 border-slate-600 text-slate-400">
                          {formatDate(d)}
                        </Badge>
                      ))}
                      {absentDatesList.length > 5 && (
                        <span className="text-[10px] text-slate-500">+{absentDatesList.length - 5} more</span>
                      )}
                    </div>
                  ) : undefined
                }
              />
            );
          })
        )}
      </div>
    </div>
  );
}

/* ───────── Fines Tab ───────── */
function FinesTab({ userId }: { userId: string }) {
  const [fines, setFines] = useState<Fine[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [finesRes, notifsRes] = await Promise.all([
        fetch('/api/fines'),
        fetch('/api/notifications?type=fine'),
      ]);
      const [finesData, notifsData] = await Promise.all([finesRes.json(), notifsRes.json()]);

      if (finesData.success) {
        let filtered = finesData.data.fines || [];
        if (yearFilter && yearFilter !== 'all') {
          filtered = filtered.filter((f: Fine) => f.createdAt.startsWith(yearFilter));
        }
        if (monthFilter && monthFilter !== 'all') {
          filtered = filtered.filter((f: Fine) => f.createdAt.substring(5, 7) === monthFilter);
        }
        setFines(filtered);
      }
      if (notifsData.success) {
        setNotifications(notifsData.data.notifications || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch fines', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [yearFilter, monthFilter]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const isUnread = (fineId: string) => {
    return notifications.some((n) => !n.read && n.type === 'fine' && n.message.includes(fineId.slice(-6)));
  };

  const handleMarkRead = async (fineId: string) => {
    try {
      const relatedNotifs = notifications.filter(
        (n) => !n.read && n.type === 'fine' && n.message.includes(fineId.slice(-6))
      );
      for (const n of relatedNotifs) {
        await fetch(`/api/notifications/${n.id}`, { method: 'PUT' });
      }
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'Marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark as read', variant: 'destructive' });
    }
  };

  const handleWhatsApp = (fine: Fine) => {
    const message = `💰 *Fine Notification*\n\n` +
      `👤 Employee: ${fine.employee.fullName}\n` +
      `🆔 ID: ${fine.employee.employeeId}\n` +
      `📋 Reason: ${fine.reason}\n` +
      `💵 Amount: ${formatCurrency(fine.amount)}\n` +
      `📅 Date: ${formatDate(fine.createdAt)}\n` +
      `\n_ASM Management System_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ markAll: true, type: 'fine' }),
      });
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      toast({ title: 'All fines marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' });
    }
  };

  const unreadCount = notifications.filter((n) => !n.read && n.type === 'fine').length;
  const totalFines = fines.reduce((sum, f) => sum + f.amount, 0);

  return (
    <div className="flex flex-col gap-4">
      {/* Summary + Filters */}
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <Select value={yearFilter} onValueChange={setYearFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Years</SelectItem>
              {YEARS.map((y) => (
                <SelectItem key={y} value={y} className="text-slate-200 focus:bg-slate-700 focus:text-white">{y}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={monthFilter} onValueChange={setMonthFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="dropdown-upward bg-slate-800 border-slate-600 max-h-64">
              <SelectItem value="all" className="text-slate-200 focus:bg-slate-700 focus:text-white">All Months</SelectItem>
              {MONTHS.map((m) => (
                <SelectItem key={m.value} value={m.value} className="text-slate-200 focus:bg-slate-700 focus:text-white">{m.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          {fines.length > 0 && (
            <Badge className="bg-amber-500/20 text-amber-400 border border-amber-500/30 text-xs px-2 py-0.5">
              Total: {formatCurrency(totalFines)}
            </Badge>
          )}
        </div>
        {unreadCount > 0 && (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleMarkAllRead}
            className="h-8 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-500/10"
          >
            <CheckCheck className="h-3.5 w-3.5 mr-1" />
            Mark All Read ({unreadCount})
          </Button>
        )}
      </div>

      {/* List */}
      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? (
          <SkeletonCards count={3} />
        ) : fines.length === 0 ? (
          <EmptyState icon={DollarSign} message="No fines found" />
        ) : (
          fines.map((f) => (
            <NotificationCard
              key={f.id}
              employeeName={f.employee.fullName}
              employeeCode={f.employee.employeeId}
              reason={f.reason}
              date={f.createdAt}
              isUnread={isUnread(f.id)}
              amount={f.amount}
              onMarkRead={() => handleMarkRead(f.id)}
              onWhatsApp={() => handleWhatsApp(f)}
            />
          ))
        )}
      </div>
    </div>
  );
}

/* ───────── Main Page ───────── */
export function NotificationPage() {
  const { user } = useAuthStore();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(true);

  const fetchNotifications = useCallback(async () => {
    try {
      const res = await fetch('/api/notifications?limit=100');
      const data = await res.json();
      if (data.success) {
        const notifs: Notification[] = data.data.notifications || [];
        setNotifications(notifs);
        setUnreadCount(notifs.filter((n) => !n.read).length);
      }
    } catch {
      // Silently fail for the count
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchNotifications(); }, [fetchNotifications]);

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ markAll: true }),
      });
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      setUnreadCount(0);
      toast({ title: 'All notifications marked as read' });
    } catch {
      toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' });
    }
  };

  const userId = user?.id || '';

  return (
    <div className="flex flex-col gap-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10">
            <Bell className="h-5 w-5 text-blue-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white flex items-center gap-2">
              Notifications
              {!loading && unreadCount > 0 && (
                <Badge className="bg-blue-500 text-white text-xs px-2 py-0.5">
                  {unreadCount}
                </Badge>
              )}
            </h2>
            <p className="text-slate-400 mt-0.5 text-sm">
              Stay updated with requests, warnings, and fines
            </p>
          </div>
        </div>
        {unreadCount > 0 && (
          <Button
            variant="outline"
            size="sm"
            onClick={handleMarkAllRead}
            className="h-8 border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700 text-xs"
          >
            <CheckCheck className="h-3.5 w-3.5 mr-1.5" />
            Mark All Read
          </Button>
        )}
      </div>

      {/* Tabs */}
      <Tabs defaultValue="requests" className="w-full">
        <TabsList className="bg-slate-800 border border-slate-700/50">
          <TabsTrigger
            value="requests"
            className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"
          >
            <FileText className="h-4 w-4" />
            Requests
          </TabsTrigger>
          <TabsTrigger
            value="warnings"
            className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"
          >
            <AlertTriangle className="h-4 w-4" />
            Warnings
          </TabsTrigger>
          <TabsTrigger
            value="fines"
            className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"
          >
            <DollarSign className="h-4 w-4" />
            Fines
          </TabsTrigger>
        </TabsList>

        <TabsContent value="requests" className="mt-4">
          <RequestsTab userId={userId} />
        </TabsContent>

        <TabsContent value="warnings" className="mt-4">
          <WarningsTab userId={userId} />
        </TabsContent>

        <TabsContent value="fines" className="mt-4">
          <FinesTab userId={userId} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
